id: P009586
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-19 20:39:25.851441
source_metadata:
  id: bdr:W8LS17253
  title: བདེ་ཆེན་ཞིང་གི་སྨོན་ལམ་གྱི་འབྱེད་འགྲེལ།
  author: ''
  volumes:
    d09269e9866e4100a38d8043b1eb2165:
      image_group_id: I8LS17280
      title: ''
      volume_number: 1
      total_pages: 124
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
